services:
  x2y:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: x2y
    volumes:
      - ..:/app:delegated
    working_dir: /app
    tty: true
    stdin_open: true
